✨ allow specifying a link for your badge
AlexBeauchemin/gobadge pull request #3
Opened 2022-10-01 07:41 UTC by acidjazz

2022-10-16 19:10 UTC, AlexBeauchemin requested changes
Thanks for your contribution
Looks good to me, just need to revert the module name change and add a test for the url and should be good to merge

2022-10-16 19:10 UTC, AlexBeauchemin commented on go.mod
> +module github.com/acidjazz/gobadge
Revert this so it can be merged

2022-10-16 19:10 UTC, AlexBeauchemin commented on gobadge_test.go
> +	err = updateReadme("unknown.md", "50.01%", "Coverage", "green", "")
Add a new test making sure the link is there when url is provided?

2023-03-19 02:44 UTC, acidjazz commented
@AlexBeauchemin i think.. i added the test correctly?

2023-03-23 12:50 UTC, AlexBeauchemin approved these changes

2023-03-23 12:50 UTC, merged