Use regex for replacing badge content
AlexBeauchemin/gobadge pull request #7
Opened 2024-03-24 18:53 UTC by mahendrapaipuri

This PR uses regular expressions to update the badge instead of string replace. The advantage of this approach is that we can keep the _custom_ format of badge in README file. 

Users can embed a "dummy" badge however they want in the README file. When we run the app, the badge will be merely updated with coverage value without losing the format.

If no badge found, it will have the same beahviour, where it will add the badge to the second line of README

2024-12-24 11:31 UTC, vtolstov commented
any chance to get this merged?

2024-12-24 17:41 UTC, AlexBeauchemin commented
Thanks for the pull request, I will take a look during the holiday and probably merge it

2025-01-01 17:03 UTC, AlexBeauchemin requested changes
Looks good to me
I would replace the goto/outside directive and replace by a break, then I'll merge it

2025-01-01 17:03 UTC, AlexBeauchemin commented on gobadge.go
> +			goto outside
Really not a fan of `goto` directive. Specially in this case where a simple break would achieve the same purpose?
```suggestion
			break
```
Then we could remove the `outside:` below which would make the code less confusing

2025-01-01 17:27 UTC, mahendrapaipuri commented on gobadge.go
> +			goto outside
Totally agree. Probably this was vestigial code.

2025-01-01 22:09 UTC, merged

2025-01-01 22:09 UTC, AlexBeauchemin commented
Thank you for your contribution! And sorry again for the delay